### PR TITLE
Update to latest funcx-endpoint lib

### PR DESCRIPTION
**Pull request by BenGalewsky**
Just a little tweak to force a rebuild of the Docker image with the latest version of the funcx-endpoint lib

### CODE REVIEW

**Comment by matthewfeickert** [comment]
Thanks @BenGalewsky!

**Comment by matthewfeickert** [comment]
@BenGalewsky This is good to make explicit the lower bound requirements :+1:, but as we have `workflow_dispatch` setup in GHA

https://github.com/Neubauer-Group/bluewaters-docker-images/blob/dbcc048bae6ac43a2222c76e84417845b382421a/.github/workflows/docker.yml#L16

we can also trigger rebuilds and redeploys manually at any time from the actions workflow panel. 

workflow_dispatch

**Comment by matthewfeickert** [comment]
@BenGalewsky Bluewaters should be ready to go now. :rocket: 

```
(base) feickert@nid25254:~> shifterimg images | grep pyhf
bluewaters docker     READY    9916787836   2021-05-20T15:25:19 neubauergroup/bluewaters-pyhf:0.6.1
bluewaters docker     READY    9916787836   2021-05-20T15:25:19 neubauergroup/bluewaters-pyhf:latest
```

**Comment by BenGalewsky** [comment]
Hmmm
I do 
```console
$ qsub -I -l gres=shifter -l nodes=1:ppn=8:xk -l walltime=01:00:00
INFO: Job submitted to account: bbdz
qsub: waiting for job 12244580.bw to start
qsub: job 12244580.bw ready

In Torque Shifter prologue batchID: 12244580
Number of nodes: 1
Starting munge and nscd service on compute nodes
uid=54939(bengal1) gid=17389(ILL_bbdz) groups=1001(hpss_user),1000(ie_user),999(login_user),17389(ILL_bbdz)
Successfully started munge and nscd service on compute nodes
----------------------------------------
Begin Torque Prologue on nid25424
at Fri May 21 10:32:43 CDT 2021
Job Id:			12244580.bw
Username:		bengal1
Group:			ILL_bbdz
Job name:		STDIN
Requested resources:	gres=shifter,nodes=1:ppn=8:xk,walltime=01:00:00,neednodes=1:ppn=8:xk
Queue:			normal
Account:		bbdz
End Torque Prologue:  11.315 elapsed
----------------------------------------
$ module load shifter
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-pyhf:0.6.1 -- /bin/bash -I
$ python -m pip list
python -m pip list
Package                Version
---------------------- ---------
brotlipy               0.7.0
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
conda                  4.9.2
conda-package-handling 1.7.2
cryptography           3.2.1
idna                   2.10
pip                    21.1.1
pycosat                0.6.3
pycparser              2.20
pyOpenSSL              19.1.0
PySocks                1.7.1
requests               2.24.0
ruamel-yaml            0.15.87
setuptools             56.2.0
six                    1.15.0
tqdm                   4.51.0
urllib3                1.25.11
wheel                  0.36.2
```
Did I forget some step? Do you get the same results?

**Comment by matthewfeickert** [comment]
@BenGalewsky Yeah, I'm confused as

```console
$ qsub -I -l gres=shifter -l nodes=1:ppn=8:xk -l walltime=01:00:00
INFO: Job submitted to account: bbdz
qsub: waiting for job 12244723.bw to start
qsub: job 12244723.bw ready

In Torque Shifter prologue batchID: 12244723
Number of nodes: 1
Starting munge and nscd service on compute nodes
uid=57956(feickert) gid=17389(ILL_bbdz) groups=1001(hpss_user),1000(ie_user),999(login_user),17389(ILL_bbdz)
Successfully started munge and nscd service on compute nodes
----------------------------------------
Begin Torque Prologue on nid27564
at Fri May 21 11:32:12 CDT 2021
Job Id:			12244723.bw
Username:		feickert
Group:			ILL_bbdz
Job name:		STDIN
Requested resources:	gres=shifter,nodes=1:ppn=8:xk,walltime=01:00:00,neednodes=1:ppn=8:xk
Queue:			normal
Account:		bbdz
End Torque Prologue:  11.355 elapsed
----------------------------------------
$ module load shifter
$ shifterimg images | grep neubauergroup/bluewaters-pyhf:0.6.1
bluewaters docker     READY    9916787836   2021-05-20T15:47:17 neubauergroup/bluewaters-pyhf:0.6.1
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-pyhf:0.6.1 -- /bin/bash -I
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
$ python -m pip list | grep funcx
funcx               0.2.3
funcx-endpoint      0.2.3
$ python -m pip list
Package             Version
------------------- ---------
attrs               21.2.0
awkward0            0.15.5
bcrypt              3.2.0
cachetools          4.2.2
certifi             2020.12.5
cffi                1.14.5
chardet             4.0.0
click               7.1.2
configobj           5.0.6
cryptography        3.4.7
cycler              0.10.0
decorator           5.0.9
dill                0.3.3
docutils            0.17.1
fair-research-login 0.2.0
funcx               0.2.3
funcx-endpoint      0.2.3
globus-sdk          2.0.1
idna                2.10
jsonpatch           1.32
jsonpointer         2.1
jsonschema          3.2.0
kiwisolver          1.3.1
lockfile            0.12.2
matplotlib          3.4.2
numpy               1.20.3
packaging           20.9
paramiko            2.7.2
parsl               1.1.0
Pillow              8.2.0
pip                 21.1.1
psutil              5.8.0
py                  1.10.0
pycparser           2.20
pyhf                0.6.1
PyJWT               1.7.1
PyNaCl              1.4.0
pyparsing           2.4.7
pyrsistent          0.17.3
python-daemon       2.3.0
python-dateutil     2.8.1
PyYAML              5.4.1
pyzmq               22.0.3
requests            2.25.1
retry               0.9.2
scipy               1.6.3
setuptools          56.2.0
six                 1.16.0
tblib               1.7.0
texttable           1.6.3
tqdm                4.60.0
typeguard           2.12.0
typer               0.3.2
typing-extensions   3.10.0.0
uproot              4.0.7
uproot3             3.14.4
uproot3-methods     0.10.1
urllib3             1.26.4
wheel               0.36.2
```

I guess we need to talk with Maxim Belkin more about what OSC containers are visible to users.

Is your

```console
$ shifterimg lookup neubauergroup/bluewaters-pyhf:0.6.1
9916787836f7893e4251be0bd2d1e8eca2cbdcd787a72372bdd13d25dd4ef8df
```

the same as mine?

**Comment by BenGalewsky** [comment]
Ah, interesting! I had installed a local version of Conda which gets activated even in my shifter images! I had to add a Conda deactivate to see the python packages in the image

**Comment by matthewfeickert** [comment]
> Ah, interesting! I had installed a local version of Conda which gets activated even in my shifter images! I had to add a Conda deactivate to see the python packages in the image

Oh that's interesting, but not super surprising given that Conda tries to force itself to be in `PATH` for _everything_. This is also interesting to learn more about how Shifter behaves, as it seems that  

```
aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-pyhf:0.6.1 -- /bin/bash -I
```

is much more like how Singularity operates with making the mounted container part of the local environment, vs. with Docker bind mounting the host machine's filepaths visible to the container but not overwriting the environment inside the container.

Example:

**Local machine:**

Obviously running without bindmounting preserves the container environment

```console
$ docker run --rm -ti neubauergroup/bluewaters-pyhf:0.6.1 'printenv'
HOSTNAME=5b1f0cbd5fe8
TERM=xterm
HISTSIZE=1000
LC_ALL=en_US.UTF-8
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
MAIL=/var/spool/mail/root
PWD=/
LANG=en_US.UTF-8
HISTCONTROL=ignoredups
HOME=/root
SHLVL=2
LOGNAME=root
_=/usr/bin/printenv
```

but bindmounting to the local machine doesn't change that

```console
$ docker run --rm -ti -v $PWD:$PWD -w $PWD neubauergroup/bluewaters-pyhf:0.6.1 'printenv'
HOSTNAME=f56903e9f06c
TERM=xterm
HISTSIZE=1000
LC_ALL=en_US.UTF-8
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
MAIL=/var/spool/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
PWD=/home/feickert/Code/GitHub/SCAILFIN/MadGraph5_aMC-NLO
LANG=en_US.UTF-8
HISTCONTROL=ignoredups
SHLVL=1
HOME=/root
LOGNAME=root
_=/usr/bin/printenv
```

vs.

**Blue Waters:**

Even if we run in an non-interactive shell we still see that the environment is _not_ just the container's

```console
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-pyhf:0.6.1 -- /bin/bash -c 'printenv' | wc -l
793
```

So there be dragons. :dragon: :(

**Comment by matthewfeickert** [comment]
> **Blue Waters:**
> 
> Even if we run in an non-interactive shell we still see that the environment is _not_ just the container's
> 
> ```console
> $ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-pyhf:0.6.1 -- /bin/bash -c 'printenv' | wc -l
> 793
> ```
> 
> So there be dragons.

Turns out that I was missing the [`shifter` `--clearenv` option](https://bluewaters.ncsa.illinois.edu/shifter#shifter-command) 

> `-E`/`--clearenv`: Don't pass environment of the MOM nodes to the compute nodes. Recommended.

```console
$ aprun -b -N 1 -- shifter --clearenv --image=neubauergroup/bluewaters-mg5_amc:3.1.0 --volume=/mnt/a/u/sciteam/$USER:/mnt/a/u/sciteam/$USER -- /bin/bash -c 'printenv'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
CPLUS_INCLUDE_PATH=/usr/local/include/python3.8
SHIFTER_MODULE_MPICH=1
LC_ALL=en_US.utf8
USER=docker
LD_LIBRARY_PATH=/opt/cray/pmi/5.0.11/lib64:/opt/cray/libsci/18.12.1/GNU/5.1/x86_64/lib:/opt/cray/mpt/7.7.4/gni/mpich-gnu-abi/5.1/lib:/opt/cray/xpmem/0.1-2.0502.64982.7.27.gem/lib64:/opt/cray/dmapp/7.0.1-1.0502.11080.8.74.gem/lib64:/opt/cray/ugni/6.0-1.0502.10863.8.28.gem/lib64:/opt/cray/udreg/2.3.2-1.0502.10518.2.17.gem/lib64:/opt/cray/wlm_detect/1.0-1.0502.64649.2.2.gem/lib64:/opt/cray/alps/5.2.4-2.0502.9774.31.12.gem/lib64:/opt/udiImage/modules/mpich/lib64:/opt/cray/nvidia/390.46-1_1.0502.2481.1.1.gem/lib64:/opt/nvidia/cudatoolkit9.1/9.1.85_3.10-1.0502.df1cc54.3.1/lib64:/usr/local/lib:
PYTHON_VERSION=3.8.10
PATH=/usr/local/MG5_aMC/bin:/home/docker/.local/bin:/opt/cray/mpt/7.7.4/gni/bin:/bin:/usr/bin:/opt/cray/nvidia/390.46-1_1.0502.2481.1.1.gem/bin:/opt/nvidia/cudatoolkit9.1/9.1.85_3.10-1.0502.df1cc54.3.1/bin:/usr/local/MG5_aMC/bin:/home/docker/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/cray/shifter/18.03.4-2/usr/lib64/shifter/opt/udiImage/bin
C_INCLUDE_PATH=/usr/local/include/python3.8
PWD=/mnt/a/u/sciteam/feickert
CUDA_VISIBLE_DEVICES=0
SHIFTER_IMAGEREQUEST=neubauergroup/bluewaters-mg5_amc:3.1.0
LANG=en_US.utf8
SHIFTER_RUNTIME=1
PYTHON_PIP_VERSION=21.1.1
SHIFTER_IMAGE=fbd9d82b3f8da9ec25997c3c04d90f16412d8ccbe02823c211d61d5e875c5a0e
SHLVL=1
HOME=/home/docker
PYTHONPATH=/usr/local/lib:/usr/local/MG5_aMC:
LESSOPEN=||/usr/bin/lesspipe.sh %s
MPICH_GNI_MALLOC_FALLBACK=1
_=/bin/printenv
Application 100609848 resources: utime ~0s, stime ~1s, Rss ~50044, inblocks ~58482, outblocks ~54213

```

**Pull request merged**
